/* Gmail tokens stay in memory and never pass through the site backend. */
(() => {
 const $=s=>document.querySelector(s), {header,parts,mime,b64bytes}=MailCore;
 const folders={INBOX:'Inbox',ALL:'All Mail',STARRED:'Starred',SENT:'Sent',DRAFT:'Drafts',SPAM:'Junk',TRASH:'Trash'};
 const accounts=new Map(); let current=null, folder='INBOX', page=null, generation=0, activeMessage=null, reply=null, siteUser=null, draftKey=null, composeAccount=null;
 const text=(tag,value,className)=>{const el=document.createElement(tag);el.textContent=value||'';if(className)el.className=className;return el;};
 const status=value=>$('#mail-status').textContent=value;
 const fail=error=>status(error.message||'Mail could not load. Please try again.');
 const isOwner=()=>siteUser?.email==='mqmrpc@gmail.com'&&siteUser?.app_metadata?.role==='admin';
 const rememberTheme=()=>{if(parent!==window){try{document.documentElement.dataset.theme=parent.document.documentElement.dataset.theme;document.documentElement.style.colorScheme=parent.document.documentElement.style.colorScheme;}catch{}}};
 rememberTheme(); if(parent!==window)try{new MutationObserver(rememberTheme).observe(parent.document.documentElement,{attributes:true,attributeFilter:['data-theme']});}catch{}
 function controls(){const connected=current&&accounts.has(current);$('#compose').disabled=!connected;$('#disconnect').disabled=!connected||current==='domain';$('#domain').hidden=!isOwner();$('#aliases').hidden=!isOwner()||current!=='domain';}
 function renderAccounts(){const box=$('#accounts');box.replaceChildren();accounts.forEach((account,key)=>{const button=text('button',account.email,'account-button');button.setAttribute('aria-current',String(key===current));button.onclick=()=>selectAccount(key);box.append(button);});controls();}
 function renderFolders(){const box=$('#folders');box.replaceChildren();Object.entries(folders).forEach(([id,name])=>{if(current==='domain'&&['DRAFT','SPAM'].includes(id))return;const button=text('button',name);button.setAttribute('aria-current',String(folder===id));button.onclick=()=>{folder=id;renderFolders();load();};box.append(button);});$('#mailbox-title').textContent=folders[folder];}
 function selectAccount(key){current=key;folder='INBOX';activeMessage=null;$('#reader').replaceChildren(text('div','Select a message to read it.','mail-empty'));renderAccounts();renderFolders();load();}
 async function gmail(path,options={},key=current){const account=accounts.get(key);if(!account||Date.now()>=account.expires)throw Error('Mail access expired. Use Add Google account to reconnect.');const response=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/'+path,{...options,headers:{Authorization:'Bearer '+account.token,'Content-Type':'application/json',...options.headers}});if(response.status===401){account.expires=0;throw Error('Mail access expired. Reconnect this Google account.');}const data=await response.json();if(!response.ok)throw Error(data.error?.message||'Google mail request failed.');return data;}
 async function domain(action,data={}){const result=await siteBackend.functions.invoke('mail-domain',{body:{action,...data}});if(result.error){let detail;try{detail=await result.error.context?.json();}catch{}throw Error(detail?.error||'Domain mail is unavailable. Please check its connection.');}if(result.data?.error)throw Error(result.data.error);return result.data;}
 $('#connect').onclick=async()=>{
  if(!siteUser){try{await signInToSite();}catch(error){fail(error);}return;}
  if(!InboxConfig.googleClientId){status('Google mail connection is being configured. Your site sign-in is unaffected.');return;}
  if(!window.google?.accounts?.oauth2){status('Google connection could not load. Check your connection and retry.');return;}
  const connectingUser=siteUser.id;
  google.accounts.oauth2.initTokenClient({client_id:InboxConfig.googleClientId,scope:'https://www.googleapis.com/auth/gmail.modify',include_granted_scopes:false,error_callback:()=>status('Google connection was closed. You can try again.'),callback:async result=>{
   if(siteUser?.id!==connectingUser)return;
   if(result.error){status('Google mail permission was not granted.');return;}
   if(!google.accounts.oauth2.hasGrantedAllScopes(result,'https://www.googleapis.com/auth/gmail.modify')){status('Grant Gmail access to connect this account.');return;}
   try{const response=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/profile',{headers:{Authorization:'Bearer '+result.access_token}});const profile=await response.json();if(!response.ok)throw Error(profile.error?.message||'Google account could not connect.');if(siteUser?.id!==connectingUser)return;accounts.set(profile.emailAddress,{email:profile.emailAddress,token:result.access_token,expires:Date.now()+Number(result.expires_in)*1000});selectAccount(profile.emailAddress);}catch(error){fail(error);}
  }}).requestAccessToken({prompt:'select_account'});
 };
 $('#disconnect').onclick=()=>{if(current==='domain')return;accounts.delete(current);current=null;generation++;activeMessage=null;$('#messages').replaceChildren();$('#reader').replaceChildren(text('div','Account disconnected from this page.','mail-empty'));renderAccounts();status('Account removed. You can also revoke Inbox access in your Google account permissions.');};
 $('#domain').onclick=()=>{accounts.set('domain',{email:'All @mqmr.bio'});selectAccount('domain');};
 function summary(message){if(current==='domain')return message;return {id:message.id,threadId:message.threadId,from:header(message,'From'),to:header(message,'To'),subject:header(message,'Subject')||'(No subject)',snippet:message.snippet,date:Number(message.internalDate),unread:message.labelIds?.includes('UNREAD'),starred:message.labelIds?.includes('STARRED'),raw:message};}
 function renderRow(message){const button=text('button','',`message-row${message.unread?' unread':''}`);button.dataset.id=message.id;const top=text('div','','message-top');top.append(text('span',message.from,'message-sender'),text('span',new Date(message.date||message.created_at).toLocaleDateString(undefined,{month:'short',day:'numeric'}),'message-date'));button.append(top,text('div',message.subject,'message-subject'),text('div',message.snippet,'message-snippet'));button.onclick=()=>read(message,button);$('#messages').append(button);}
 async function load(append=false){if(!current){status('Add a Google account to connect your mail.');return;}const key=current,ticket=++generation;status('Loading mail…');$('#more').hidden=true;if(!append){page=null;$('#messages').replaceChildren();}try{let messages,next;
  if(key==='domain'){const result=await domain('list',{folder,search:$('#search').value,cursor:append?page:null});messages=result.messages;next=result.next;}
  else {const params=new URLSearchParams({maxResults:'25'});if(folder!=='ALL')params.set('labelIds',folder);if($('#search').value)params.set('q',$('#search').value);if(append&&page)params.set('pageToken',page);const result=await gmail('messages?'+params,{},key);next=result.nextPageToken;messages=[];const ids=result.messages||[];for(let i=0;i<ids.length;i+=5){const batch=await Promise.all(ids.slice(i,i+5).map(item=>gmail(`messages/${item.id}?format=metadata&metadataHeaders=From&metadataHeaders=To&metadataHeaders=Subject`,{},key)));messages.push(...batch);}}
  if(ticket!==generation||key!==current)return;messages.map(summary).forEach(renderRow);page=next;$('#more').hidden=!page;$('#mailbox-count').textContent=current==='domain'?'All addresses at @mqmr.bio':current;status(messages.length?'':append?'No more messages.':'No messages in this mailbox.');
 }catch(error){if(ticket===generation)fail(error);}}
 $('#refresh').onclick=()=>load();$('#more').onclick=()=>load(true);$('#search').onkeydown=event=>{if(event.key==='Enter')load();};$('#search').onsearch=()=>load();
 async function read(message,button){const key=current,ticket=++generation;status('Opening message…');try{const full=key==='domain'?await domain('read',{id:message.id}):await gmail('messages/'+message.id+'?format=full',{},key);if(ticket!==generation||key!==current)return;activeMessage={...message,full};document.querySelectorAll('.message-row').forEach(row=>row.classList.toggle('selected',row===button));button.classList.remove('unread');const reader=$('#reader');reader.replaceChildren(text('h2',message.subject,'reader-subject'));reader.append(text('div',`From: ${message.from}\nTo: ${message.to}\n${new Date(message.date||message.created_at).toLocaleString()}`,'reader-meta'));const actions=text('div','','reader-actions');
  const action=(label,fn)=>{const el=text('button',label);el.onclick=async()=>{el.disabled=true;try{await fn();}catch(error){fail(error);}finally{el.disabled=false;}};actions.append(el);};
  action('Reply',()=>compose(message));action(message.starred?'Unstar':'Star',async()=>{await modify(message.id,{starred:!message.starred},key);message.starred=!message.starred;await read(message,button);});action('Mark unread',async()=>{await modify(message.id,{unread:true},key);button.classList.add('unread');});if(folder!=='TRASH')action('Move to Trash',async()=>{await modify(message.id,{trash:true},key);reader.replaceChildren(text('p','Message moved to Trash.'));load();});else action('Restore',async()=>{await modify(message.id,{trash:false},key);load();});if(folder==='INBOX')action('Archive',async()=>{await modify(message.id,{archive:true},key);reader.replaceChildren(text('p','Message archived.'));load();});reader.append(actions);
  const content=key==='domain'?{text:full.text_body,html:full.html_body,files:full.attachments||[]}:parts(full.payload);const plain=content.text||(content.html?new DOMParser().parseFromString(content.html,'text/html').body.textContent:'');reader.append(text('pre',plain||'(No message body)','mail-text'));
  const files=text('div','','file-list');content.files.forEach(file=>{const download=text('button','↓ '+file.name);download.onclick=async()=>{download.disabled=true;try{const result=file.data?{data:file.data}:key==='domain'?await domain('attachment',{id:message.id,attachment:file.id}):await gmail(`messages/${message.id}/attachments/${file.id}`,{},key);const bytes=b64bytes(result.data);const blob=new Blob([bytes],{type:'application/octet-stream'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=file.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){fail(error);}finally{download.disabled=false;}};files.append(download);});reader.append(files);status('');if(message.unread){await modify(message.id,{unread:false},key);message.unread=false;}
 }catch(error){if(ticket===generation)fail(error);}}
 async function modify(id,change,key=current){if(key==='domain')return domain('modify',{id,...change});if('trash'in change)return gmail(`messages/${id}/${change.trash?'trash':'untrash'}`,{method:'POST'},key);const addLabelIds=[],removeLabelIds=[];if('starred'in change)(change.starred?addLabelIds:removeLabelIds).push('STARRED');if('unread'in change)(change.unread?addLabelIds:removeLabelIds).push('UNREAD');if(change.archive)removeLabelIds.push('INBOX');return gmail(`messages/${id}/modify`,{method:'POST',body:JSON.stringify({addLabelIds,removeLabelIds})},key);}
 async function addresses(){const result=await domain('addresses');return result.addresses;}
 async function compose(message=null){try{composeAccount=current;reply=message;draftKey=crypto.randomUUID();const from=$('#from');from.replaceChildren();const values=composeAccount==='domain'?(await addresses()).map(a=>a.address):[composeAccount];values.forEach(value=>{const option=text('option',value);option.value=value;from.append(option);});$('#to').value=message?composeAccount==='domain'?message.full.reply_to||message.from:header(message.full,'Reply-To')||message.from:'';const email=$('#to').value.match(/<([^>]+)>/);if(email)$('#to').value=email[1];$('#subject').value=message?(/^Re:/i.test(message.subject)?message.subject:'Re: '+message.subject):'';$('#body').value='';$('#attachments').value='';$('#compose-status').textContent='';$('#compose-dialog').showModal();$('#to').focus();}catch(error){fail(error);}}
 $('#compose').onclick=()=>compose();$('#close-compose').onclick=()=>$('#compose-dialog').close();
 $('#compose-form').onsubmit=async event=>{event.preventDefault();const button=$('#send'),key=composeAccount;button.disabled=true;$('#compose-status').textContent='Sending…';try{const selected=[...$('#attachments').files];if(selected.reduce((sum,file)=>sum+file.size,0)>10*1024*1024)throw Error('Attachments must total 10 MB or less.');const files=await Promise.all(selected.map(async file=>({name:file.name,type:file.type,content:btoa(Array.from(new Uint8Array(await file.arrayBuffer()),b=>String.fromCharCode(b)).join(''))})));const data={from:$('#from').value,to:$('#to').value,subject:$('#subject').value,text:$('#body').value,files,idempotencyKey:draftKey};if(key==='domain')await domain('send',data);else await gmail('messages/send',{method:'POST',body:JSON.stringify({raw:mime({...data,replyId:reply?header(reply.full,'Message-ID'):null}),...(reply?{threadId:reply.threadId}:{})})},key);$('#compose-dialog').close();status('Message sent.');draftKey=null;}catch(error){$('#compose-status').textContent=error.message;}finally{button.disabled=false;}};
 async function listAliases(){const items=await addresses();$('#alias-list').replaceChildren(...items.map(a=>text('li',a.address)));}
 $('#aliases').onclick=async()=>{try{await listAliases();$('#alias-dialog').showModal();}catch(error){fail(error);}};$('#close-aliases').onclick=()=>$('#alias-dialog').close();$('#alias-form').onsubmit=async event=>{event.preventDefault();try{await domain('add-address',{name:$('#alias-name').value});await listAliases();$('#alias-name').value='';$('#alias-status').textContent='Address added.';}catch(error){$('#alias-status').textContent=error.message;}};
 async function updateUser(){const {data,error}=await siteBackend.auth.getUser();const next=error?null:data.user;if(siteUser?.id&&siteUser.id!==next?.id){accounts.clear();current=null;generation++;$('#messages').replaceChildren();$('#reader').replaceChildren(text('div','Sign in and reconnect your mail.','mail-empty'));}siteUser=next;renderAccounts();}
 siteBackend.auth.onAuthStateChange(()=>setTimeout(updateUser,0));updateUser();renderFolders();
})();
